[versions]
# Android Gradle Plugin
agp = "8.13.1"
# Kotlin
kotlin = "2.2.0"
kotlinCoroutines = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
collectionImmutable = "0.4.0"
# Android
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
#Google Services
googleServices = "4.4.4"
#Compose
composeBom = "2024.09.00"
navigationCompose = "2.9.3"
#Dependency Injection
javaInject = "1"
hilt = "2.58"
hiltNavigationCompose = "1.3.0"
#ksp
ksp = "2.2.0-2.0.2"
#Timber
timber = "5.0.1"
#Serialization
serialization = "1.10.0"
appcompat = "1.7.1"
material = "1.13.0"

#ImageLoader
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
#Firebase
firebase-bom = "34.9.0"
crashlytics = "3.0.6"
#Retrofit
retrofit = "3.0.0"
# Moshi
moshi = "1.15.2"

[libraries]
# Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
#Kotlin
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref ="kotlinxCoroutinesTest" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "collectionImmutable" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name ="kotlin-test-junit", version.ref ="kotlin" }
#Dependency Injection
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaInject" }
#Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
#ImageLoader
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
#Logger
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
#Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
#Moshi
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
#Hilt
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
#Ksp
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# Compose
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
#Kotlin Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#Google services
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
#Crashlytics
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
#Cvshowcase Custom Plugins
cvshowcase-application = { id = "cvshowcase.application" }
cvshowcase-library = { id = "cvshowcase.library" }
cvshowcase-jvm-library = { id = "cvshowcase.jvm.library" }
cvshowcase-feature= { id = "cvshowcase.feature" }
cvshowcase-hilt = { id = "cvshowcase.hilt" }
cvshowcase-compose-navigation = { id = "cvshowcase.compose.navigation" }
cvshowcase-flavors = { id = "cvshowcase.flavors" }


